definitions:
  models.AddRatingRequest:
    properties:
      comment:
        type: string
      rating:
        type: number
      user_id:
        type: string
    type: object
  product_service.AddProductCategoryRequest:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  product_service.AddProductCategoryResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  product_service.AddProductRequest:
    properties:
      artisan_id:
        type: string
      category_id:
        type: string
      description:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  product_service.AddProductResponse:
    properties:
      artisan_id:
        type: string
      category_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  product_service.AddRatingResponse:
    properties:
      comment:
        type: string
      created_at:
        type: string
      id:
        type: string
      product_id:
        type: string
      rating:
        type: number
      user_id:
        type: string
    type: object
  product_service.DeleteProductResponse:
    properties:
      message:
        type: string
    type: object
  product_service.EditProductRequest:
    properties:
      artisan_id:
        type: string
      category_id:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
    type: object
  product_service.EditProductResponse:
    properties:
      artisan_id:
        type: string
      category_id:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
  product_service.Product:
    properties:
      artisan_id:
        type: string
      category_id:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
  product_service.Rating:
    properties:
      comment:
        type: string
      created_at:
        type: string
      id:
        type: string
      product_id:
        type: string
      rating:
        type: number
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a restaurant reservation system.
  title: Artisan Connect
  version: "1.0"
paths:
  /api/v1/categories/product:
    post:
      consumes:
      - application/json
      description: Create new category for Product
      parameters:
      - description: product category
        in: body
        name: Product_Category
        required: true
        schema:
          $ref: '#/definitions/product_service.AddProductCategoryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product_service.AddProductCategoryResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create New Category for Product
      tags:
      - Product Category
  /api/v1/products/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product by id
      parameters:
      - description: Product ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product_service.DeleteProductResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete Product
      tags:
      - Product
    get:
      consumes:
      - application/json
      description: Get a Product by its ID
      parameters:
      - description: Product ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product_service.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a Product
      tags:
      - Product
    put:
      consumes:
      - application/json
      description: Update a new product
      parameters:
      - description: product_id
        in: path
        name: Product_id
        required: true
        type: string
      - description: Update
        in: body
        name: UpdateProduct
        required: true
        schema:
          $ref: '#/definitions/product_service.EditProductRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/product_service.EditProductResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update Product
      tags:
      - Product
  /api/v1/products/{id}/ratings:
    get:
      consumes:
      - application/json
      description: Get all ratings for a product
      parameters:
      - description: Product ID
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/product_service.Rating'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all ratings for a product
      tags:
      - Product
  /api/v1/products/{product_id}/rate:
    post:
      consumes:
      - application/json
      description: Rate a product
      parameters:
      - description: Product ID
        format: uuid
        in: path
        name: product_id
        required: true
        type: string
      - description: rating a product
        in: body
        name: AddRatingRequest
        required: true
        schema:
          $ref: '#/definitions/models.AddRatingRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/product_service.AddRatingResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Rate A Product
      tags:
      - Product
  /api/v1/products/all:
    get:
      consumes:
      - application/json
      description: get all products in page by limit
      parameters:
      - description: limit
        in: query
        name: limit
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/product_service.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get All Products
      tags:
      - Product
  /api/v1/products/create:
    post:
      consumes:
      - application/json
      description: Creating a new product
      parameters:
      - description: Create
        in: body
        name: Add_Product_Request
        required: true
        schema:
          $ref: '#/definitions/product_service.AddProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/product_service.AddProductResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Product
      tags:
      - Product
  /api/v1/products/search:
    post:
      consumes:
      - application/json
      description: Get a Product by its ID
      parameters:
      - description: product name
        in: query
        name: query
        type: string
      - description: category name
        in: query
        name: category
        type: string
      - description: minimum price
        in: query
        name: min_price
        type: string
      - description: maximum price
        in: query
        name: max_price
        type: string
      - description: limit
        in: query
        name: limit
        type: string
      - description: page
        in: query
        name: page
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/product_service.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a Product
      tags:
      - Product
swagger: "2.0"
